import type { Metadata } from "next";
import "./globals.css";
import { play, poppins } from "./fonts/font";
//import Link from "next/link";
import Navbar from "./components/navbar";
import { SerwistProvider } from "@serwist/turbopack/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
    >
      <body className={`${play.className}`} style={{height:"100vh"}}>
        {/* <Navbar/> */}
        <SerwistProvider swUrl="/serwist/sw.js">
        {children}
        </SerwistProvider>
        </body>
    </html>
  );
}

// function Chargement() {

//   return(
//      <html>
//     <body className="bg-green-400">
//       <h1 className="h-full w-full text-amber-300">BIENVENUE CHEZ, <br /><span className="font-bold text-2xl text-green-700">AgroConnect</span></h1>
//     </body>
//   </html>
//   )
 
// }